//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_P2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int Id { get; set; }
        public Nullable<double> Count { get; set; }
        public int GoodId { get; set; }
        public int ChekId { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Chek Chek { get; set; }
    }
}
